/*
 * Generated by Autumn Generator.
 * 
 * Copyright 2006 the original author or authors.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "LowerAction_Wrapper.h"

/**
 * Wrapper methods for LowerAction
 */
void* LowerAction_Wrapper::execCreateMethod(string& method, void** Prams, int num)
{
	if( !method.compare("getMessage") && num == 0 )
		return (void*)(this->pBean->getMessage());
	if( !method.compare("excute") && num == 1 )
		return (void*)(this->pBean->excute(
				*(char**)Prams[0]));
	if( !method.compare("LowerAction") && num == 0 )
		return (void*)(this->pBean = new LowerAction());

	return NULL;
}

int LowerAction_Wrapper::execVoidMethod(string& method, void** Prams, int num)
{
	if( !method.compare("setMessage") && num == 1 )
		this->pBean->setMessage(
					 *(char**)Prams[0]);
	else 
		return -1;

	return 0;
}

int LowerAction_Wrapper::getParamTypes(string& method, string& types, int num)
{
	if( !method.compare("getMessage") && num == 0 )
		types = string("");
	else if( !method.compare("setMessage") && num == 1 )
		types = string("")
			  + "char*|";
	else if( !method.compare("excute") && num == 1 )
		types = string("")
			  + "char*|";
	else if( !method.compare("LowerAction") && num == 0 )
		types = string("");
	else 
		return -1;

	return 0;
}

void* LowerAction_Wrapper::cast2Base(const string basename)
{
	if( basename == "Action" )
		return (Action*)(this->pBean);

	return this->pBean;
}

extern "C"{
	IBeanWrapper* create_LowerAction_Wrapper(){
		return new LowerAction_Wrapper;
	}
	void delete_LowerAction_Wrapper(IBeanWrapper* p){
		delete p;
	}
}

AUTUMN_LowerAction_Wrapper_Local _AUTUMN_LowerAction_Wrapper_Local_;

