.SUFFIXES:	.cpp .o

CXX=aCC
CXXFLAGS=-AA +z -I.
CXXLDFLAGS=-b

include makefile.objects


all:libAutumn.so 

.cpp.o:
	$(CXX) $(CXXFLAGS) -c $<

libAutumn.so:$(OBJS)
	 $(CXX) $(CXXLDFLAGS) -o $@ $(OBJS)

clean:
	rm -f *.o ./libAutumn.so

install:

