/*
 * Generated by Autumn Generator.
 * 
 * Copyright 2006 the original author or authors.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef LOCALBEAN_WRAPPER_H
#define LOCALBEAN_WRAPPER_H

#include "IBeanWrapper.h"
#include "LocalBean.h"

/**
 * Wrapper for LocalBean
 */
class LocalBean_Wrapper: public IBeanWrapper{
	LocalBean* pBean;

public: 
	LocalBean_Wrapper(){
		this->setBeanName("LocalBean");
		this->pBean = NULL;
	}

	~LocalBean_Wrapper(){
		if( this->pBean && !this->deleteBean() )
			delete this->pBean;
	}

	void* getBean(){ return (void*)this->pBean; }
	void  setBean(void* p){
		this->pBean = (LocalBean*)p;
	}

	void* execCreateMethod(string& method, void** Prams, int num);

	int execVoidMethod(string& method, void** Prams, int num);

	int getParamTypes(string& method, string& types, int num);

	void* cast2Base(const string basename);

};

extern "C"{
	DLL_EXPORT IBeanWrapper* create_LocalBean_Wrapper();
	DLL_EXPORT void delete_LocalBean_Wrapper(IBeanWrapper*);
}

class AUTUMN_LocalBean_Wrapper_Local{
public:
	AUTUMN_LocalBean_Wrapper_Local(){
		registerLocalFunction(
				"create_LocalBean_Wrapper",
				(void*)create_LocalBean_Wrapper);
		registerLocalFunction(
				"delete_LocalBean_Wrapper",
				(void*)delete_LocalBean_Wrapper);
	}
};

#endif
