/*
 * Generated by Autumn Generator.
 * 
 * Copyright 2006 the original author or authors.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "Factories_Wrapper.h"

/**
 * Wrapper methods for Factory1
 */
void* Factory1_Wrapper::execCreateMethod(string& method, void** Prams, int num)
{
	if( !method.compare("createProductA") && num == 1 )
		return this->pBean->createProductA(
				*(string*)Prams[0]);
	if( !method.compare("createProductB") && num == 1 )
		return this->pBean->createProductB(
				*(string*)Prams[0]);
	if( !method.compare("createProductC") && num == 0 )
		return this->pBean->createProductC();
	if( !method.compare("Factory1") && num == 0 )
		return this->pBean = new Factory1();

	return NULL;
}

int Factory1_Wrapper::execVoidMethod(string& method, void** Prams, int num)
{
	return -1;
}

int Factory1_Wrapper::getParamTypes(string& method, string& types, int num)
{
	if( !method.compare("createProductA") && num == 1 )
		types = string("")
			  + "string|";
	else if( !method.compare("createProductB") && num == 1 )
		types = string("")
			  + "string|";
	else if( !method.compare("createProductC") && num == 0 )
		types = string("");
	else if( !method.compare("Factory1") && num == 0 )
		types = string("");
	else 
		return -1;

	return 0;
}

extern "C"{
	IBeanWrapper* create_Factory1_Wrapper(){
		return new Factory1_Wrapper;
	}
	void delete_Factory1_Wrapper(IBeanWrapper* p){
		delete p;
	}
}

AUTUMN_Factory1_Wrapper_Local _AUTUMN_Factory1_Wrapper_Local_;

/**
 * Wrapper methods for Factory2
 */
void* Factory2_Wrapper::execCreateMethod(string& method, void** Prams, int num)
{
	if( !method.compare("createProductA") && num == 1 )
		return this->pBean->createProductA(
				*(string*)Prams[0]);
	if( !method.compare("createProductB") && num == 1 )
		return this->pBean->createProductB(
				*(string*)Prams[0]);
	if( !method.compare("createProductC") && num == 0 )
		return this->pBean->createProductC();
	if( !method.compare("Factory2") && num == 0 )
		return this->pBean = new Factory2();

	return NULL;
}

int Factory2_Wrapper::execVoidMethod(string& method, void** Prams, int num)
{
	return -1;
}

int Factory2_Wrapper::getParamTypes(string& method, string& types, int num)
{
	if( !method.compare("createProductA") && num == 1 )
		types = string("")
			  + "string|";
	else if( !method.compare("createProductB") && num == 1 )
		types = string("")
			  + "string|";
	else if( !method.compare("createProductC") && num == 0 )
		types = string("");
	else if( !method.compare("Factory2") && num == 0 )
		types = string("");
	else 
		return -1;

	return 0;
}

extern "C"{
	IBeanWrapper* create_Factory2_Wrapper(){
		return new Factory2_Wrapper;
	}
	void delete_Factory2_Wrapper(IBeanWrapper* p){
		delete p;
	}
}

AUTUMN_Factory2_Wrapper_Local _AUTUMN_Factory2_Wrapper_Local_;

