
#include "BeanWrapperMacro.h"
#include "Factories.h"

AUTUMNBEAN(Factory1)

AUTUMNBEAN_CREATOR()
AUTUMNBEAN_CONSTRUCTOR(Factory1)
AUTUMNBEAN_CON_MAKER_1P(createProductA, string)
AUTUMNBEAN_CON_MAKER_1P(createProductB, string)
AUTUMNBEAN_CON_MAKER(createProductC)
AUTUMNBEAN_CREATOR_END()

AUTUMNBEAN_END(Factory1)

AUTUMNBEAN(Factory2)

AUTUMNBEAN_CREATOR()
AUTUMNBEAN_CONSTRUCTOR(Factory2)
AUTUMNBEAN_CON_MAKER_1P(createProductA, string)
AUTUMNBEAN_CON_MAKER_1P(createProductB, string)
AUTUMNBEAN_CON_MAKER(createProductC)
AUTUMNBEAN_CREATOR_END()

AUTUMNBEAN_END(Factory2)



