/*
 * Generated by Autumn Generator.
 * 
 * Copyright 2006 the original author or authors.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef FACTORIES_WRAPPER_H
#define FACTORIES_WRAPPER_H

#include "IBeanWrapper.h"
#include "Factories.h"

/**
 * Wrapper for Factory1
 */
class Factory1_Wrapper: public IBeanWrapper{
	Factory1* pBean;

public: 
	Factory1_Wrapper(){
		this->setBeanName("Factory1");
		this->pBean = NULL;
	}

	~Factory1_Wrapper(){
		if( this->pBean && !this->deleteBean() )
			delete this->pBean;
	}

	void* getBean(){ return (void*)this->pBean; }
	void  setBean(void* p){
		this->pBean = (Factory1*)p;
	}

	void* execCreateMethod(string& method, void** Prams, int num);

	int execVoidMethod(string& method, void** Prams, int num);

	int getParamTypes(string& method, string& types, int num);

};

extern "C"{
	DLL_EXPORT IBeanWrapper* create_Factory1_Wrapper();
	DLL_EXPORT void delete_Factory1_Wrapper(IBeanWrapper*);
}

class AUTUMN_Factory1_Wrapper_Local{
public:
	AUTUMN_Factory1_Wrapper_Local(){
		registerLocalFunction(
				"create_Factory1_Wrapper",
				(void*)create_Factory1_Wrapper);
		registerLocalFunction(
				"delete_Factory1_Wrapper",
				(void*)delete_Factory1_Wrapper);
	}
};

/**
 * Wrapper for Factory2
 */
class Factory2_Wrapper: public IBeanWrapper{
	Factory2* pBean;

public: 
	Factory2_Wrapper(){
		this->setBeanName("Factory2");
		this->pBean = NULL;
	}

	~Factory2_Wrapper(){
		if( this->pBean && !this->deleteBean() )
			delete this->pBean;
	}

	void* getBean(){ return (void*)this->pBean; }
	void  setBean(void* p){
		this->pBean = (Factory2*)p;
	}

	void* execCreateMethod(string& method, void** Prams, int num);

	int execVoidMethod(string& method, void** Prams, int num);

	int getParamTypes(string& method, string& types, int num);

};

extern "C"{
	DLL_EXPORT IBeanWrapper* create_Factory2_Wrapper();
	DLL_EXPORT void delete_Factory2_Wrapper(IBeanWrapper*);
}

class AUTUMN_Factory2_Wrapper_Local{
public:
	AUTUMN_Factory2_Wrapper_Local(){
		registerLocalFunction(
				"create_Factory2_Wrapper",
				(void*)create_Factory2_Wrapper);
		registerLocalFunction(
				"delete_Factory2_Wrapper",
				(void*)delete_Factory2_Wrapper);
	}
};

#endif
