/*
 * Generated by Autumn Generator.
 * 
 * Copyright 2006 the original author or authors.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef IPRODUCT_WRAPPER_H
#define IPRODUCT_WRAPPER_H

#include "IBeanWrapper.h"
#include "IProduct.h"

/**
 * Wrapper for IProductA
 */
class IProductA_Wrapper: public IBeanWrapper{
	IProductA* pBean;

public: 
	IProductA_Wrapper(){
		this->setBeanName("IProductA");
		this->pBean = NULL;
	}

	~IProductA_Wrapper(){
		if( this->pBean && !this->deleteBean() )
			delete this->pBean;
	}

	void* getBean(){ return (void*)this->pBean; }
	void  setBean(void* p){
		this->pBean = (IProductA*)p;
	}

	void* execCreateMethod(string& method, void** Prams, int num);

	int execVoidMethod(string& method, void** Prams, int num);

	int getParamTypes(string& method, string& types, int num);

	void* cast2Base(const string basename);

};

extern "C"{
	DLL_EXPORT IBeanWrapper* create_IProductA_Wrapper();
	DLL_EXPORT void delete_IProductA_Wrapper(IBeanWrapper*);
}

class AUTUMN_IProductA_Wrapper_Local{
public:
	AUTUMN_IProductA_Wrapper_Local(){
		registerLocalFunction(
				"create_IProductA_Wrapper",
				(void*)create_IProductA_Wrapper);
		registerLocalFunction(
				"delete_IProductA_Wrapper",
				(void*)delete_IProductA_Wrapper);
	}
};

/**
 * Wrapper for IProductB
 */
class IProductB_Wrapper: public IBeanWrapper{
	IProductB* pBean;

public: 
	IProductB_Wrapper(){
		this->setBeanName("IProductB");
		this->pBean = NULL;
	}

	~IProductB_Wrapper(){
		if( this->pBean && !this->deleteBean() )
			delete this->pBean;
	}

	void* getBean(){ return (void*)this->pBean; }
	void  setBean(void* p){
		this->pBean = (IProductB*)p;
	}

	void* execCreateMethod(string& method, void** Prams, int num);

	int execVoidMethod(string& method, void** Prams, int num);

	int getParamTypes(string& method, string& types, int num);

	void* cast2Base(const string basename);

};

extern "C"{
	DLL_EXPORT IBeanWrapper* create_IProductB_Wrapper();
	DLL_EXPORT void delete_IProductB_Wrapper(IBeanWrapper*);
}

class AUTUMN_IProductB_Wrapper_Local{
public:
	AUTUMN_IProductB_Wrapper_Local(){
		registerLocalFunction(
				"create_IProductB_Wrapper",
				(void*)create_IProductB_Wrapper);
		registerLocalFunction(
				"delete_IProductB_Wrapper",
				(void*)delete_IProductB_Wrapper);
	}
};

/**
 * Wrapper for IProductC
 */
class IProductC_Wrapper: public IBeanWrapper{
	IProductC* pBean;

public: 
	IProductC_Wrapper(){
		this->setBeanName("IProductC");
		this->pBean = NULL;
	}

	~IProductC_Wrapper(){
		if( this->pBean && !this->deleteBean() )
			delete this->pBean;
	}

	void* getBean(){ return (void*)this->pBean; }
	void  setBean(void* p){
		this->pBean = (IProductC*)p;
	}

	void* execCreateMethod(string& method, void** Prams, int num);

	int execVoidMethod(string& method, void** Prams, int num);

	int getParamTypes(string& method, string& types, int num);

	void* cast2Base(const string basename);

};

extern "C"{
	DLL_EXPORT IBeanWrapper* create_IProductC_Wrapper();
	DLL_EXPORT void delete_IProductC_Wrapper(IBeanWrapper*);
}

class AUTUMN_IProductC_Wrapper_Local{
public:
	AUTUMN_IProductC_Wrapper_Local(){
		registerLocalFunction(
				"create_IProductC_Wrapper",
				(void*)create_IProductC_Wrapper);
		registerLocalFunction(
				"delete_IProductC_Wrapper",
				(void*)delete_IProductC_Wrapper);
	}
};

#endif
