
#include "BeanWrapperMacro.h"
#include "SingletonBean.h"
#include "InitDestBean.h"
#include "SelfManagedBean.h"

AUTUMNBEAN(SingletonBean)

AUTUMNBEAN_CREATOR()
AUTUMNBEAN_CONSTRUCTOR(SingletonBean)
AUTUMNBEAN_CREATOR_END()

AUTUMNBEAN_SETTER()
AUTUMNBEAN_PROPERTY(String, string)
AUTUMNBEAN_SETTER_END()
AUTUMNBEAN_END(SingletonBean)



AUTUMNBEAN(InitDestBean)

AUTUMNBEAN_CREATOR()
AUTUMNBEAN_CONSTRUCTOR_1P(InitDestBean, SingletonBean*)
AUTUMNBEAN_CREATOR_END()

AUTUMNBEAN_INIT(initialize)
AUTUMNBEAN_DESTROY(destroy)
AUTUMNBEAN_END(InitDestBean)



AUTUMNBEAN(SelfManagedBean)

AUTUMNBEAN_CREATOR()
AUTUMNBEAN_CONSTRUCTOR_1P(SelfManagedBean, SingletonBean*)
AUTUMNBEAN_CREATOR_END()

AUTUMNBEAN_SETTER()
AUTUMNBEAN_PROPERTY(CStr, char*)
AUTUMNBEAN_SETTER_END()
AUTUMNBEAN_END(SelfManagedBean)
