/*
 * Copyright 2006 the original author or authors.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <fstream>
#include <sstream>
#include <cctype>
#include "GenException.h"
#include "Util.h"
#include "ElmtFactory.h"
#include "HeadFile.h"

HeadFile::HeadFile(string infile)
{
	string fileContent, rest;

	this->filename = Util::filenameOf(infile);
	this->readFile(infile, fileContent);

	int idx = 0, ridx;
	while( idx <fileContent.size() ){
		rest = fileContent.substr(idx);

		if( ridx = Util::irrelevantLen(rest) ){
			idx += ridx;
		}
		else{
			IElement* e = ElmtFactory::makeElmt(fileContent, idx);
			if( e == NULL ){
				throw GenException("Unrecognised file part.", 
						Util::lineno(fileContent, idx));
			}
			this->Elements.push_back(e);
		}
	}
}

HeadFile::~HeadFile()
{
	for( int i=0; i<this->Elements.size(); i++)
		delete this->Elements[i];
}

void HeadFile::genWrapper(string outfile)
{
	ofstream wf(outfile.c_str());
	if( !wf.is_open() ){
		throw GenException("Can't open file to write: " + outfile);
	}

	wf << this->licenseInfo();
	wf << "#include \"" << this->filename << "\"" << endl;
	wf << endl;
	
	string s;
	for( int i=0; i<this->Elements.size(); i++){
		IElement* e = this->Elements[i];

		// only generate namespace and class
		if( e->getType() == IElement::NAMESAPCE ||
				e->getType() == IElement::CLASS ){
			wf << e->genWrapperPart();
			wf <<endl;
		}
	}

	wf.close();
}

void HeadFile::readFile(string infile, string& content)
{
	ifstream hf(infile.c_str());
	if( !hf.is_open() ){
		throw GenException("Can't open file to read: " + infile);
	}

	string s;
	while( getline(hf, s) ){
		content = content + s + "\n";
	}

	hf.close();
}

string HeadFile::licenseInfo()
{
	ostringstream s;
	s<<
	"/*" <<endl <<
	" * Generated by Autumn Generator." << endl <<
	" * " << endl <<
	" * Copyright 2006 the original author or authors." << endl <<
	" * " << endl <<
	" * Licensed under the Apache License, Version 2.0 (the \"License\");" << endl <<
	" * you may not use this file except in compliance with the License." << endl <<
	" * You may obtain a copy of the License at" << endl <<
	" * " << endl <<
	" *      http://www.apache.org/licenses/LICENSE-2.0" << endl <<
	" * " << endl <<
	" * Unless required by applicable law or agreed to in writing, software" << endl <<
	" * distributed under the License is distributed on an \"AS IS\" BASIS," << endl <<
	" * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied." << endl <<
	" * See the License for the specific language governing permissions and" << endl <<
	" * limitations under the License." << endl <<
	" */" << endl<<
	endl;
	
	return s.str();
}