
#include "BeanWrapperMacro.h"
#include "LowerAction.h"
#include "UpperAction.h"


AUTUMNBEAN(LowerAction)

AUTUMNBEAN_CREATOR()
AUTUMNBEAN_CONSTRUCTOR(LowerAction)
AUTUMNBEAN_CREATOR_END()

AUTUMNBEAN_SETTER()
AUTUMNBEAN_PROPERTY(Message, char*)
AUTUMNBEAN_SETTER_END()
AUTUMNBEAN_END(LowerAction)

AUTUMNBEAN(UpperAction)

AUTUMNBEAN_CREATOR()
AUTUMNBEAN_CONSTRUCTOR(UpperAction)
AUTUMNBEAN_CREATOR_END()

AUTUMNBEAN_SETTER()
AUTUMNBEAN_PROPERTY(Message, char*)
AUTUMNBEAN_SETTER_END()
AUTUMNBEAN_END(UpperAction)

