
#include "BeanWrapperMacro.h"
#include "BasicTypesBean.h"

AUTUMNBEAN(BasicTypesBean)

AUTUMNBEAN_CONSTRUCTOR(BasicTypesBean)

AUTUMNBEAN_CON_PARAMS(BasicTypesBean, 13, char)
AUTUMNBEAN_CON_PARAM(unsigned char)
AUTUMNBEAN_CON_PARAM(short		)
AUTUMNBEAN_CON_PARAM(unsigned short)
AUTUMNBEAN_CON_PARAM(int			)
AUTUMNBEAN_CON_PARAM(unsigned int)
AUTUMNBEAN_CON_PARAM(long		)
AUTUMNBEAN_CON_PARAM(unsigned long)
AUTUMNBEAN_CON_PARAM(float		)
AUTUMNBEAN_CON_PARAM(double		)
AUTUMNBEAN_CON_PARAM(string		)
AUTUMNBEAN_CON_PARAM(char*		)
AUTUMNBEAN_CON_PARAM(unsigned char*)
AUTUMNBEAN_CON_PARAMS_END()

AUTUMNBEAN_SETTER()
AUTUMNBEAN_PROPERTY(Char,char)	
AUTUMNBEAN_PROPERTY(UChar,unsigned char)
AUTUMNBEAN_PROPERTY(Short,short	)	
AUTUMNBEAN_PROPERTY(UShort,unsigned short)
AUTUMNBEAN_PROPERTY(Int,int		)	
AUTUMNBEAN_PROPERTY(UInt,unsigned int)
AUTUMNBEAN_PROPERTY(Long,long	)	
AUTUMNBEAN_PROPERTY(ULong,unsigned long)
AUTUMNBEAN_PROPERTY(Float,float	)	
AUTUMNBEAN_PROPERTY(Double,double	)	
AUTUMNBEAN_PROPERTY(String,string)		
AUTUMNBEAN_PROPERTY(CStr,char*	)	
AUTUMNBEAN_PROPERTY(UCStr,unsigned char*)

AUTUMNBEAN_PROPERTY(IntP,int*		)	
AUTUMNBEAN_PROPERTY(CStrP,char**	)	
AUTUMNBEAN_SETTER_END()

AUTUMNBEAN_END(BasicTypesBean)
