
#include "BeanWrapperMacro.h"
#include "MultiInheriteBean.h"

AUTUMNBEAN(Multi_Base1)
AUTUMNBEAN_CREATOR()
AUTUMNBEAN_CONSTRUCTOR(Multi_Base1)
AUTUMNBEAN_CREATOR_END()
AUTUMNBEAN_END(Multi_Base1)

AUTUMNBEAN(Multi_Base2)
AUTUMNBEAN_CREATOR()
AUTUMNBEAN_CONSTRUCTOR(Multi_Base2)
AUTUMNBEAN_CREATOR_END()
AUTUMNBEAN_END(Multi_Base2)

AUTUMNBEAN(Multi_Bean)
AUTUMNBEAN_CREATOR()
AUTUMNBEAN_CONSTRUCTOR(Multi_Bean)
AUTUMNBEAN_CREATOR_END()
AUTUMNBEAN_END(Multi_Bean)