
#include "BeanWrapperMacro.h"
#include "MyBasicType.h"
#include "MyTypeBean.h"

// MyBasicType
//AUTUMNTYPE(MyBasicType)
AUTUMNBEAN(MyBasicType)
AUTUMNBEAN_CREATOR()
AUTUMNBEAN_CONSTRUCTOR(MyBasicType)
AUTUMNBEAN_CREATOR_END()
AUTUMNBEAN_END(MyBasicType)

// MyTypeBean
AUTUMNBEAN(MyTypeBean)
AUTUMNBEAN_CREATOR()
AUTUMNBEAN_CONSTRUCTOR(MyTypeBean)
AUTUMNBEAN_CREATOR_END()

AUTUMNBEAN_SETTER()
AUTUMNBEAN_PROPERTY(MyData, MyData*)
AUTUMNBEAN_SETTER_END()
AUTUMNBEAN_END(MyTypeBean)
