/*
 * Generated by Autumn Generator.
 * 
 * Copyright 2006 the original author or authors.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef SELFMANAGEDBEAN_WRAPPER_H
#define SELFMANAGEDBEAN_WRAPPER_H

#include "IBeanWrapper.h"
#include "SelfManagedBean.h"

/**
 * Wrapper for SelfManagedBean
 */
class SelfManagedBean_Wrapper: public Autumn::IBeanWrapper{
	SelfManagedBean* pBean;

public: 
	SelfManagedBean_Wrapper(){
		this->setBeanName("SelfManagedBean");
		this->pBean = NULL;
	}

	~SelfManagedBean_Wrapper(){
		if( this->pBean && !this->deleteBean() )
			delete this->pBean;
	}

	void* getBean(){ return (void*)this->pBean; }
	void  setBean(void* p){
		this->pBean = (SelfManagedBean*)p;
	}

	void* execCreateMethod(string& method, void** Prams, int num);

	int execVoidMethod(string& method, void** Prams, int num);

	int getParamTypes(string& method, string& types, int num);

	void* cast2Base(const string basename);

};

extern "C"{
	DLL_EXPORT Autumn::IBeanWrapper* create_SelfManagedBean_Wrapper();
	DLL_EXPORT void delete_SelfManagedBean_Wrapper(Autumn::IBeanWrapper*);
}

class AUTUMN_SelfManagedBean_Wrapper_Local{
public:
	AUTUMN_SelfManagedBean_Wrapper_Local(){
		Autumn::registerLocalFunction(
				"create_SelfManagedBean_Wrapper",
				(void*)create_SelfManagedBean_Wrapper);
		Autumn::registerLocalFunction(
				"delete_SelfManagedBean_Wrapper",
				(void*)delete_SelfManagedBean_Wrapper);
	}
};

#endif
