/*
 * Generated by Autumn Generator.
 * 
 * Copyright 2006 the original author or authors.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "FileLogger_Wrapper.h"

/**
 * Wrapper methods for FileLogger
 */
void* FileLogger_Wrapper::execCreateMethod(string& method, void** Prams, int num)
{
	if( !method.compare("FileLogger") && num == 2 )
		return (void*)(this->pBean = new FileLogger(
				*(string*)Prams[0],
				*(int*)Prams[1]));

	return NULL;
}

int FileLogger_Wrapper::execVoidMethod(string& method, void** Prams, int num)
{
	if( !method.compare("debug") && num == 1 )
		this->pBean->debug(
					 *(string*)Prams[0]);
	else if( !method.compare("info") && num == 1 )
		this->pBean->info(
					 *(string*)Prams[0]);
	else if( !method.compare("warn") && num == 1 )
		this->pBean->warn(
					 *(string*)Prams[0]);
	else if( !method.compare("error") && num == 1 )
		this->pBean->error(
					 *(string*)Prams[0]);
	else if( !method.compare("fatal") && num == 1 )
		this->pBean->fatal(
					 *(string*)Prams[0]);
	else if( !method.compare("log") && num == 2 )
		this->pBean->log(
					 *(int*)Prams[0],
					 *(string*)Prams[1]);
	else 
		return -1;

	return 0;
}

int FileLogger_Wrapper::getParamTypes(string& method, string& types, int num)
{
	if( !method.compare("FileLogger") && num == 2 )
		types = string("")
			  + "string|"
			  + "int|";
	else if( !method.compare("debug") && num == 1 )
		types = string("")
			  + "string|";
	else if( !method.compare("info") && num == 1 )
		types = string("")
			  + "string|";
	else if( !method.compare("warn") && num == 1 )
		types = string("")
			  + "string|";
	else if( !method.compare("error") && num == 1 )
		types = string("")
			  + "string|";
	else if( !method.compare("fatal") && num == 1 )
		types = string("")
			  + "string|";
	else if( !method.compare("log") && num == 2 )
		types = string("")
			  + "int|"
			  + "string|";
	else 
		return -1;

	return 0;
}

void* FileLogger_Wrapper::cast2Base(const string basename)
{
	if( basename == "ILogAdapter" )
		return (ILogAdapter*)(this->pBean);

	return this->pBean;
}

extern "C"{
	IBeanWrapper* create_FileLogger_Wrapper(){
		return new FileLogger_Wrapper;
	}
	void delete_FileLogger_Wrapper(IBeanWrapper* p){
		delete p;
	}
}

AUTUMN_FileLogger_Wrapper_Local _AUTUMN_FileLogger_Wrapper_Local_;

