/*
 * Generated by Autumn Generator.
 * 
 * Copyright 2006 the original author or authors.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef FILELOGGER_WRAPPER_H
#define FILELOGGER_WRAPPER_H

#include "IBeanWrapper.h"
#include "FileLogger.h"

/**
 * Wrapper for FileLogger
 */
class FileLogger_Wrapper: public IBeanWrapper{
	FileLogger* pBean;

public: 
	FileLogger_Wrapper(){
		this->setBeanName("FileLogger");
		this->pBean = NULL;
	}

	~FileLogger_Wrapper(){
		if( this->pBean && !this->deleteBean() )
			delete this->pBean;
	}

	void* getBean(){ return (void*)this->pBean; }
	void  setBean(void* p){
		this->pBean = (FileLogger*)p;
	}

	void* execCreateMethod(string& method, void** Prams, int num);

	int execVoidMethod(string& method, void** Prams, int num);

	int getParamTypes(string& method, string& types, int num);

};

extern "C"{
	DLL_EXPORT IBeanWrapper* create_FileLogger_Wrapper();
	DLL_EXPORT void delete_FileLogger_Wrapper(IBeanWrapper*);
}

class AUTUMN_FileLogger_Wrapper_Local{
public:
	AUTUMN_FileLogger_Wrapper_Local(){
		registerLocalFunction(
				"create_FileLogger_Wrapper",
				(void*)create_FileLogger_Wrapper);
		registerLocalFunction(
				"delete_FileLogger_Wrapper",
				(void*)delete_FileLogger_Wrapper);
	}
};

#endif
