.SUFFIXES:	.cpp .o

CXX=xlC_r
CXXFLAGS=-I.
CXXLDFLAGS=-p 0 -G

include makefile.objects


all:libAutumn.so 

.cpp.o:
	$(CXX) $(CXXFLAGS) -c $<

libAutumn.so:$(OBJS)
	 makeC++SharedLib $(CXXLDFLAGS) -o $@ $(OBJS)

clean:
	rm -f *.o ./libAutumn.so

install:

