.SUFFIXES:	.cpp .o

CXX=c++
CXXFLAGS=-I. -fPIC
CXXLDFLAGS=-fPIC -shared

include makefile.objects


all:libAutumn.so 

.cpp.o:
	$(CXX) $(CXXFLAGS) -c $<

libAutumn.so:$(OBJS)
	 $(CXX) $(CXXLDFLAGS) -o $@ $(OBJS)

clean:
	rm -f *.o ./libAutumn.so

install:

